### PR TITLE
DNB Updates to index, javascript, css and contributors

### PR DESCRIPTION
**Pull request by DionneNoellaBarretto**
replaced the cursor to be a pointer for all hoverable links, added padding for the header section, shrunk the padding for the how do you feel div, removed unused classes, changed the images in the cards to be cover sized instead of stretch, tweaked the modal container to be gradient colored + include the author and last modified quote date, changed the display for the results to be 3 in a row and more than 8 (by default <20), removed the marker variable that wasn't used in javascript, updated the contributor's page footer section, cleaned up the code in index majorly"

### CODE REVIEW

**Comment by DionneNoellaBarretto** [comment]
+refined the index code and also added a gradual hover over cards

**Comment by DionneNoellaBarretto** [comment]
+ added the logic to fetch users location from local storage

**Comment by DionneNoellaBarretto** [comment]
fixed the results cards sizing to display in a row grid format..

**Comment by DionneNoellaBarretto** [comment]
removed backup files and also updated readme..

**Review by hlbrown — APPROVED** [review]

**Pull request merged**
